# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				chicken = true
				axolotl = true
				bee = true
				donkey = true
				cow = true
				tropical_fish = true
				fox = true
				pig = true
				slime = true
				skeleton = true
				iron_golem = true
				bat = true
				cat = true
				rabbit = true
				zombie = true
				drowned = true
				sheep = true
				player = true
				dolphin = true
				item = true
				wolf = true
				villager = true
				salmon = true
				zombie_villager = true
				horse = true
				cave_spider = true
				witch = true
				glow_squid = true
				cod = true
				glow_item_frame = false
				squid = true
				spider = true
				creeper = true
				enderman = true

			[light_sources.settings.entities.tconstruct]
				sky_slime = true

			[light_sources.settings.entities.livingthings]
				shark = true
				mantaray = true
				raccoon = true
				owl = true
				crab = true
				seahorse = true

			[light_sources.settings.entities.endermanoverhaul]
				savanna_enderman = true
				flower_fields_enderman = true
				cave_enderman = true
				dark_oak_enderman = true

			[light_sources.settings.entities.creeperoverhaul]
				bamboo_creeper = true
				dripstone_creeper = true
				jungle_creeper = true
				cave_creeper = true
				hills_creeper = true

			[light_sources.settings.entities.friendsandfoes]
				glare = true
				mauler = true
				rascal = true

			[light_sources.settings.entities.lootr]
				lootr_minecart = true

			[light_sources.settings.entities.biomeswevegone]
				oddion = true

